### ISSUE TITLE
Beer

### ISSUE THREAD

**Issue by dsorce** [RobU23/ReaScripts#16]
Would like to purchase a beer for you Rob but need some specific info. 
http://www.pintprice.com/region.php?/United%20Kingdom/
Is 3 GBP a sufficient amount?

**Comment by vanhaze2000** [comment]
Yes ! Many thx !

**Comment by RobU23** [comment]
hello ! 

beer comes in many sizes and _**any**_ contribution is more than welcome

If you have any suggestions for features or fixes, be sure to donate those here too :) 

cheers
Rob
