### ISSUE TITLE
reaper 5.70/64 fail to run

### ISSUE THREAD

**Issue by magwa101** [RobU23/ReaScripts#19]
Imported via ReaPack, Load and Run via Actions and got this error:
RobU - MIDI Ex Machina.lua:416: bad argument #1 to 'GetMediaItemInfo_Value' (MediaItem expected)

Not sure if you're maintaining, I will look at this too since I'm learning Lua.

**Comment by magwa101** [comment]
Ahh, I opened the Midi Editor first, now it works.

**Comment by RobU23** [comment]
Hey hey - yeah, it only runs in the MIDI Editor as you've discovered, it shouldn't have created an action in the main action list (unless you did it yourself...).

I'm still maintaining it, but the current architecture is a bit all over the place as it sort of grew as I was learning Lua :)  I'm rewriting the GUI, then I'll port it across, but will be a few months until it gets to beta ... 

Anyways - have fun with it, and if you do find any bugs, please report them here, or send me a PM on the Reaper forum.

Cheers
Rob
