### ISSUE TITLE
Script error when running - attempt to call a nil value

### ISSUE THREAD

**Issue by viperx77** [RobU23/ReaScripts#22]
RobU - MIDI Ex Machina.lua:403: attempt to call a nil value (field 'BR_GetMidiSourceLenPPQ')

I installed through ReaScript and I'm in the MIDI Editor.

**Comment by RobU23** [comment]
Hi.  The script is making a call to a function called 'BR_GetMidiSourceLenPPQ', but that function is not a part of the native Reaper API, you need to install the latest SWS extensions from http://sws-extension.org/

This was a recent change that was made to fix a bug.  I've updated the Wiki to show the dependency.

Cheers.

**Comment by viperx77** [comment]
Cool beans! Thanks.
