### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by katyasehgal** [RobU23/ReaScripts#27]
First time user - this is the error I receive. 

...s/MIDI Editor/MIDI Ex Machina/RobU - MIDI Ex Machina.lua:676: attempt to call a nil value (field 'BR_GetMidiSourceLenPPQ')

These are the settings I want

![Uploading Screenshot from 2023-09-19 18-31-18.png…]()

**Comment by RobU23** [comment]
Hi - I'm surprised that anyone is still using this, the code-base is old and quite crufty ! :) 

That said, if you are determined...  : )   you will need to install SWS Extensions for Reaper, the script depends on them for some functionality. 

Hope this helps!

**Comment by katyasehgal** [comment]
Thank you. I installed SWS and got it working some 30 seconds back. I trust this will help me. Thank you for your hard work.
