### ISSUE TITLE
Shift notes left/right by grid value in sequencer

### ISSUE THREAD

**Issue by RobU23** [RobU23/ReaScripts#9]
Allow the sequencer to non-destructively shift note data left or right by x grid spaces, wrapping round the current item.

**Comment by RobU23** [comment]
added
version bump to 1.3.2

**Comment by ThrashJazzAssassin** [comment]
v1.3.3 - Repeatedly hitting >> on a looped MIDI item moves the loop point
![midi ex machina](https://user-images.githubusercontent.com/15689085/52635411-b6af0500-2ec1-11e9-8de3-18a520e82c4e.gif)

**Comment by RobU23** [comment]
Heh... 
Thanks for the report, I'll revisit the shifter code.

**Comment by RobU23** [comment]
Fixed in v1.3.4 - Update available in Repack.
